-- only two user roles - 1 = employee, 2 = finance manager
INSERT INTO project1.ERS_USER_ROLES (USER_ROLE) VALUES ('Employee');
INSERT INTO project1.ERS_USER_ROLES (USER_ROLE) VALUES ('Manager');

-- only three reimbursement statuses - 1 = pending, 2 = approved, 3 = denied
INSERT INTO project1.ERS_REIMBURSEMENT_STATUS (REIMB_STATUS) VALUES ('Pending');
INSERT INTO project1.ERS_REIMBURSEMENT_STATUS (REIMB_STATUS) VALUES ('Approved');
INSERT INTO project1.ERS_REIMBURSEMENT_STATUS (REIMB_STATUS) VALUES ('Denied');

-- only four reimbursement types - 1 = LODGING, 2 = TRAVEL, 3 = FOOD, 4 = OTHER
INSERT INTO project1.ERS_REIMBURSEMENT_TYPE (REIMB_TYPE) VALUES ('LODGING');
INSERT INTO project1.ERS_REIMBURSEMENT_TYPE (REIMB_TYPE) VALUES ('TRAVEL');
INSERT INTO project1.ERS_REIMBURSEMENT_TYPE (REIMB_TYPE) VALUES ('FOOD');
INSERT INTO project1.ERS_REIMBURSEMENT_TYPE (REIMB_TYPE) VALUES ('OTHER');

-- test user - employee
INSERT INTO project1.ERS_USERS (ERS_USERNAME, ERS_PASSWORD, USER_FIRST_NAME, 
USER_LAST_NAME, USER_EMAIL, USER_ROLE_ID) VALUES
('emp1', 'test', 'john', 'buck', 'jb@gmail.com', 1);

-- test user - manager
INSERT INTO project1.ERS_USERS (ERS_USERNAME, ERS_PASSWORD, USER_FIRST_NAME, 
USER_LAST_NAME, USER_EMAIL, USER_ROLE_ID) VALUES
('mngr1', 'test', 'jane', 'doe', 'jd@gmail.com', 2);

-- test reimb - NOT RESOLVED
INSERT INTO project1.ERS_REIMBURSEMENT (REIMB_AMOUNT, REIMB_SUBMITTED, 
REIMB_DESCRIPTION, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID) VALUES
(250, CURRENT_TIMESTAMP, 'Certification Exam Passed', 1, 1, 4);